In [1]:
# Read in data and packages
import pandas as pd
import numpy as np

df = pd.read_csv('ML1_data_adj_v2.csv')

In [2]:
df1 = df.drop(columns=['Date', 'ticker', 'Year', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M_v5Y', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df1.describe()

,Fwd_Best_EPS_6M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROIC_SD,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD
count,52663.000000,5.266300e+04,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,...,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000
mean,0.158580,3.856277e+04,0.148181,0.166686,0.161365,0.166059,0.195058,0.233565,0.758739,0.734770,...,3.556086,22.037783,0.538209,8.729163,15.678287,1.158177,5.093014,20.137485,0.407036,2.290982
std,0.300668,1.190055e+05,0.623256,0.375157,0.263672,0.209388,0.172892,0.219233,1.898438,1.258768,...,7.658581,19.601373,39.290832,29.708889,15.673818,19.740105,13.935295,12.905475,3.487581,2.611346
min,-0.988708,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,0.102878,-16.261128,-1911.423912,0.131123,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187
25%,0.000000,4.286605e+03,0.000000,-0.001739,0.008633,0.051301,0.094444,0.109806,0.000000,0.038221,...,1.313910,10.480123,-2.172367,1.814120,6.092163,-1.903933,1.692893,10.227462,-0.783936,0.837488
50%,0.106354,1.101040e+04,0.000000,0.067773,0.110053,0.128617,0.155689,0.171661,0.356882,0.609129,...,2.236108,15.982763,0.623657,3.301677,12.791814,0.634537,2.881977,17.616442,0.222127,1.553496
75%,0.290000,2.807057e+04,0.061876,0.279279,0.275222,0.244966,0.249250,0.280383,1.527506,1.481357,...,3.874265,27.194794,4.589976,7.030059,24.105201,3.499139,4.744545,27.380663,1.531564,2.916092
max,1.993151,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,267.476144,191.928086,146.501760,804.087967,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769

In [3]:
from pycaret.regression import *

In [4]:
reg_experiment = setup(df1, target = 'Fwd_Best_EPS_6M', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M')

In [5]:
best_model = compare_models(fold=10)

In [6]:
et1 = create_model('et')

In [7]:
evaluate_model(et1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [ ]:
#plot_model(et1)

In [ ]:
#interpret_model(et1)

In [ ]:
#predictions = predict_model(et1)

In [8]:
# EPS_6M_v5Y
# Read in data and packages
df2 = df.drop(columns=['Date', 'ticker', 'Year', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df2.describe()

,Fwd_Best_EPS_6M_v5Y,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROIC_SD,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD
count,52663.000000,5.266300e+04,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,...,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000
mean,0.642501,3.856277e+04,0.148181,0.166686,0.161365,0.166059,0.195058,0.233565,0.758739,0.734770,...,3.556086,22.037783,0.538209,8.729163,15.678287,1.158177,5.093014,20.137485,0.407036,2.290982
std,1.953389,1.190055e+05,0.623256,0.375157,0.263672,0.209388,0.172892,0.219233,1.898438,1.258768,...,7.658581,19.601373,39.290832,29.708889,15.673818,19.740105,13.935295,12.905475,3.487581,2.611346
min,-9.950293,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,0.102878,-16.261128,-1911.423912,0.131123,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187
25%,0.000000,4.286605e+03,0.000000,-0.001739,0.008633,0.051301,0.094444,0.109806,0.000000,0.038221,...,1.313910,10.480123,-2.172367,1.814120,6.092163,-1.903933,1.692893,10.227462,-0.783936,0.837488
50%,0.539640,1.101040e+04,0.000000,0.067773,0.110053,0.128617,0.155689,0.171661,0.356882,0.609129,...,2.236108,15.982763,0.623657,3.301677,12.791814,0.634537,2.881977,17.616442,0.222127,1.553496
75%,1.474491,2.807057e+04,0.061876,0.279279,0.275222,0.244966,0.249250,0.280383,1.527506,1.481357,...,3.874265,27.194794,4.589976,7.030059,24.105201,3.499139,4.744545,27.380663,1.531564,2.916092
max,9.900663,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,267.476144,191.928086,146.501760,804.087967,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769

In [9]:
from pycaret.regression import *

In [12]:
reg_experiment = setup(df2, target = 'Fwd_Best_EPS_6M_v5Y', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M_v5Y')

In [13]:
best_model = compare_models(fold=10)

In [14]:
et2 = create_model('et')

In [15]:
evaluate_model(et2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [16]:
# EPS_Accel_3M
# Read in data and packages
df3 = df.drop(columns=['Date', 'ticker', 'Fwd_ST_Accel_Class_3M', 'Sector','Fwd_Best_EPS_6M', 'Fwd_Best_EPS_6M_v5Y','Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df3.describe()

,Fwd_ST_Accel_3M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD,Year
count,52663.000000,5.266300e+04,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,...,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000,52663.000000
mean,49.725362,3.856277e+04,0.148181,0.166686,0.161365,0.166059,0.195058,0.233565,0.758739,0.734770,...,22.037783,0.538209,8.729163,15.678287,1.158177,5.093014,20.137485,0.407036,2.290982,2018.664299
std,22.730477,1.190055e+05,0.623256,0.375157,0.263672,0.209388,0.172892,0.219233,1.898438,1.258768,...,19.601373,39.290832,29.708889,15.673818,19.740105,13.935295,12.905475,3.487581,2.611346,1.280851
min,0.000000,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,-16.261128,-1911.423912,0.131123,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187,2016.000000
25%,32.600000,4.286605e+03,0.000000,-0.001739,0.008633,0.051301,0.094444,0.109806,0.000000,0.038221,...,10.480123,-2.172367,1.814120,6.092163,-1.903933,1.692893,10.227462,-0.783936,0.837488,2018.000000
50%,49.333333,1.101040e+04,0.000000,0.067773,0.110053,0.128617,0.155689,0.171661,0.356882,0.609129,...,15.982763,0.623657,3.301677,12.791814,0.634537,2.881977,17.616442,0.222127,1.553496,2019.000000
75%,66.700000,2.807057e+04,0.061876,0.279279,0.275222,0.244966,0.249250,0.280383,1.527506,1.481357,...,27.194794,4.589976,7.030059,24.105201,3.499139,4.744545,27.380663,1.531564,2.916092,2020.000000
max,99.200000,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,191.928086,146.501760,804.087967,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769,2021.000000

In [17]:
reg_experiment = setup(df3, target = 'Fwd_ST_Accel_3M', session_id=123, log_experiment=True, experiment_name='Fwd_ST_Accel_3M')

In [19]:
best_model = compare_models(fold=10)

In [20]:
et3 = create_model('et')

In [21]:
evaluate_model(et3)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦