In [1]:
# Read in data and packages
import pandas as pd
import numpy as np


df = pd.read_csv('ML1_data_adj.csv')

In [2]:
df1 = df.drop(columns=['Date', 'ticker', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M_v5Y', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df1.describe()

,Fwd_Best_EPS_6M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD,Return_1M,Return_3M,Return_6M,Rel_PMO
count,53038.000000,5.303800e+04,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,...,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000
mean,0.158638,3.835033e+04,0.148228,0.166827,0.161853,0.166631,0.195041,0.233895,0.758473,0.736787,...,15.599725,1.158496,5.077143,20.069130,0.405133,2.285190,0.520072,1.862740,4.276252,3.151893
std,0.300568,1.186151e+05,0.625187,0.376203,0.264095,0.209114,0.172556,0.219335,1.901434,1.260438,...,15.652384,19.677183,13.887346,12.893932,3.483056,2.602929,6.658470,12.139324,18.281649,16.197264
min,-0.988708,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187,-54.161013,-70.666545,-75.242145,-60.382400
25%,0.000000,4.245892e+03,0.000000,-0.002300,0.008621,0.051814,0.094658,0.109910,0.000000,0.038153,...,6.040077,-1.910111,1.696937,10.173997,-0.782032,0.840695,-3.275774,-5.749933,-7.521906,-7.368425
50%,0.106219,1.096426e+04,0.000000,0.067597,0.110497,0.128809,0.155875,0.171925,0.356882,0.609823,...,12.695624,0.635479,2.880945,17.502968,0.219938,1.548242,0.432533,1.457611,3.205198,2.133950
75%,0.290389,2.789657e+04,0.061856,0.280374,0.276894,0.246178,0.250000,0.280383,1.528308,1.482824,...,24.022028,3.510489,4.725833,27.343203,1.531597,2.904808,4.128587,8.712265,14.232692,12.129600
max,1.993151,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769,53.753221,130.215010,222.820193,141.610500

In [3]:
from pycaret.regression import *

In [4]:
reg_experiment = setup(df1, target = 'Fwd_Best_EPS_6M', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M')

In [5]:
best_model = compare_models(fold=10)

In [6]:
et1 = create_model('et')

In [7]:
evaluate_model(et1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [ ]:
plot_model(et1)

In [ ]:
interpret_model(et1)

In [ ]:
predictions = predict_model(et1)

In [8]:
# EPS_6M_v5Y
# Read in data and packages
df2 = df.drop(columns=['Date', 'ticker', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df2.describe()

,Fwd_Best_EPS_6M_v5Y,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD,Return_1M,Return_3M,Return_6M,Rel_PMO
count,53038.000000,5.303800e+04,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,...,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000
mean,0.644013,3.835033e+04,0.148228,0.166827,0.161853,0.166631,0.195041,0.233895,0.758473,0.736787,...,15.599725,1.158496,5.077143,20.069130,0.405133,2.285190,0.520072,1.862740,4.276252,3.151893
std,1.952677,1.186151e+05,0.625187,0.376203,0.264095,0.209114,0.172556,0.219335,1.901434,1.260438,...,15.652384,19.677183,13.887346,12.893932,3.483056,2.602929,6.658470,12.139324,18.281649,16.197264
min,-9.950293,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187,-54.161013,-70.666545,-75.242145,-60.382400
25%,0.000000,4.245892e+03,0.000000,-0.002300,0.008621,0.051814,0.094658,0.109910,0.000000,0.038153,...,6.040077,-1.910111,1.696937,10.173997,-0.782032,0.840695,-3.275774,-5.749933,-7.521906,-7.368425
50%,0.539209,1.096426e+04,0.000000,0.067597,0.110497,0.128809,0.155875,0.171925,0.356882,0.609823,...,12.695624,0.635479,2.880945,17.502968,0.219938,1.548242,0.432533,1.457611,3.205198,2.133950
75%,1.474221,2.789657e+04,0.061856,0.280374,0.276894,0.246178,0.250000,0.280383,1.528308,1.482824,...,24.022028,3.510489,4.725833,27.343203,1.531597,2.904808,4.128587,8.712265,14.232692,12.129600
max,9.900663,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769,53.753221,130.215010,222.820193,141.610500

In [9]:
from pycaret.regression import *

In [10]:
reg_experiment = setup(df2, target = 'Fwd_Best_EPS_6M_v5Y', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M_v5Y')

In [11]:
best_model = compare_models(fold=10)

In [12]:
et2 = create_model('et')

In [13]:
evaluate_model(et2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [14]:
# EPS_Accel_3M
# Read in data and packages
df3 = df.drop(columns=['Date', 'ticker', 'Fwd_ST_Accel_Class_3M', 'Sector','Fwd_Best_EPS_6M', 'Fwd_Best_EPS_6M_v5Y','Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df3.describe()

,Fwd_ST_Accel_3M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD,Return_1M,Return_3M,Return_6M,Rel_PMO
count,53038.000000,5.303800e+04,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,...,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000,53038.000000
mean,49.752170,3.835033e+04,0.148228,0.166827,0.161853,0.166631,0.195041,0.233895,0.758473,0.736787,...,15.599725,1.158496,5.077143,20.069130,0.405133,2.285190,0.520072,1.862740,4.276252,3.151893
std,22.738380,1.186151e+05,0.625187,0.376203,0.264095,0.209114,0.172556,0.219335,1.901434,1.260438,...,15.652384,19.677183,13.887346,12.893932,3.483056,2.602929,6.658470,12.139324,18.281649,16.197264
min,0.000000,3.249532e+02,-2.993548,-1.406977,-0.919422,-0.543590,-0.203883,-0.107213,-7.953953,-3.993373,...,-53.640777,-682.186460,0.171153,-3.379768,-83.005348,0.040187,-54.161013,-70.666545,-75.242145,-60.382400
25%,32.633333,4.245892e+03,0.000000,-0.002300,0.008621,0.051814,0.094658,0.109910,0.000000,0.038153,...,6.040077,-1.910111,1.696937,10.173997,-0.782032,0.840695,-3.275774,-5.749933,-7.521906,-7.368425
50%,49.366667,1.096426e+04,0.000000,0.067597,0.110497,0.128809,0.155875,0.171925,0.356882,0.609823,...,12.695624,0.635479,2.880945,17.502968,0.219938,1.548242,0.432533,1.457611,3.205198,2.133950
75%,66.733333,2.789657e+04,0.061856,0.280374,0.276894,0.246178,0.250000,0.280383,1.528308,1.482824,...,24.022028,3.510489,4.725833,27.343203,1.531597,2.904808,4.128587,8.712265,14.232692,12.129600
max,99.200000,2.317310e+06,5.985646,3.917949,1.993151,1.970179,1.985257,1.996078,7.994405,3.997175,...,192.327044,473.918884,315.433750,79.827790,45.481836,54.359769,53.753221,130.215010,222.820193,141.610500

In [15]:
reg_experiment = setup(df3, target = 'Fwd_ST_Accel_3M', session_id=123, log_experiment=True, experiment_name='Fwd_ST_Accel_3M')

In [16]:
best_model = compare_models(fold=10)

In [17]:
et3 = create_model('et')

In [18]:
evaluate_model(et3)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦