In [1]:
# Read in data and packages
import pandas as pd
import numpy as np

df = pd.read_csv('ML1_data_adj_v2_2020.csv')

In [2]:
df1 = df.drop(columns=['Date', 'ticker', 'Year', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M_v5Y', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df1.describe()

,Fwd_Best_EPS_6M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROIC_SD,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD
count,9655.000000,9.655000e+03,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,...,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000
mean,0.203561,4.873435e+04,0.131042,0.154172,0.104790,0.082954,0.189046,0.224295,0.623089,0.373428,...,4.436768,23.128603,0.714566,10.081576,16.712635,1.599437,5.077914,19.949077,0.241283,2.256996
std,0.378586,1.589189e+05,0.712215,0.440149,0.274208,0.182191,0.151355,0.221054,2.415437,1.432303,...,12.549713,20.775341,15.693921,28.630527,17.378893,9.759347,15.022525,11.868889,3.391683,2.924381
min,-0.988708,4.562085e+02,-2.926829,-1.384615,-0.919422,-0.442396,-0.170858,-0.107213,-7.953953,-3.993373,...,0.102878,-12.375649,-472.845019,0.240854,-53.640777,-138.502299,0.277630,0.991808,-31.670424,0.043836
25%,-0.004433,4.665172e+03,-0.011928,-0.016713,-0.044319,-0.018127,0.090515,0.100719,-0.068293,-0.211718,...,1.594859,11.220107,-2.717843,2.261763,7.884683,-1.286033,1.828516,10.670374,-0.774170,0.908480
50%,0.169680,1.350816e+04,0.000000,0.107740,0.076464,0.068636,0.157016,0.162899,0.527363,0.384920,...,2.623948,16.978441,0.073115,4.078987,14.462899,1.429506,2.987927,17.819475,0.275584,1.481325
75%,0.381862,3.294946e+04,0.129252,0.333115,0.222041,0.164483,0.253289,0.265465,1.883838,1.256368,...,4.350258,27.836253,3.284567,9.001750,25.205843,4.321343,4.692301,26.382385,1.499902,2.888305
max,1.993151,2.138671e+06,5.963361,3.557447,1.901235,1.970179,1.952381,1.984000,7.994405,3.994267,...,267.476144,171.365332,118.384365,483.121134,189.810606,276.603059,268.684445,70.454544,26.242878,54.359769

In [3]:
from pycaret.regression import *

In [4]:
reg_experiment = setup(df1, target = 'Fwd_Best_EPS_6M', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M')

In [5]:
best_model = compare_models(fold=10)

In [8]:
cat1 = create_model('catboost')

In [9]:
evaluate_model(cat1)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [ ]:
#plot_model(et1)

In [ ]:
#interpret_model(et1)

In [ ]:
#predictions = predict_model(et1)

In [10]:
# EPS_6M_v5Y
# Read in data and packages
df2 = df.drop(columns=['Date', 'ticker', 'Year', 'Fwd_ST_Accel_Class_3M', 'Fwd_ST_Accel_3M','Sector','Fwd_Best_EPS_6M', 'Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df2.describe()

,Fwd_Best_EPS_6M_v5Y,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROIC_SD,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD
count,9655.000000,9.655000e+03,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,...,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000
mean,0.602173,4.873435e+04,0.131042,0.154172,0.104790,0.082954,0.189046,0.224295,0.623089,0.373428,...,4.436768,23.128603,0.714566,10.081576,16.712635,1.599437,5.077914,19.949077,0.241283,2.256996
std,2.373250,1.589189e+05,0.712215,0.440149,0.274208,0.182191,0.151355,0.221054,2.415437,1.432303,...,12.549713,20.775341,15.693921,28.630527,17.378893,9.759347,15.022525,11.868889,3.391683,2.924381
min,-9.914735,4.562085e+02,-2.926829,-1.384615,-0.919422,-0.442396,-0.170858,-0.107213,-7.953953,-3.993373,...,0.102878,-12.375649,-472.845019,0.240854,-53.640777,-138.502299,0.277630,0.991808,-31.670424,0.043836
25%,-0.027446,4.665172e+03,-0.011928,-0.016713,-0.044319,-0.018127,0.090515,0.100719,-0.068293,-0.211718,...,1.594859,11.220107,-2.717843,2.261763,7.884683,-1.286033,1.828516,10.670374,-0.774170,0.908480
50%,0.847408,1.350816e+04,0.000000,0.107740,0.076464,0.068636,0.157016,0.162899,0.527363,0.384920,...,2.623948,16.978441,0.073115,4.078987,14.462899,1.429506,2.987927,17.819475,0.275584,1.481325
75%,1.857984,3.294946e+04,0.129252,0.333115,0.222041,0.164483,0.253289,0.265465,1.883838,1.256368,...,4.350258,27.836253,3.284567,9.001750,25.205843,4.321343,4.692301,26.382385,1.499902,2.888305
max,9.804447,2.138671e+06,5.963361,3.557447,1.901235,1.970179,1.952381,1.984000,7.994405,3.994267,...,267.476144,171.365332,118.384365,483.121134,189.810606,276.603059,268.684445,70.454544,26.242878,54.359769

In [11]:
from pycaret.regression import *

In [12]:
reg_experiment = setup(df2, target = 'Fwd_Best_EPS_6M_v5Y', session_id=123, log_experiment=True, experiment_name='Fwd_EPS_6M_v5Y')

In [13]:
best_model = compare_models(fold=10)

In [14]:
cat2 = create_model('catboost')

In [15]:
evaluate_model(cat2)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [17]:
# EPS_Accel_3M
# Read in data and packages
df3 = df.drop(columns=['Date', 'ticker', 'Year', 'Fwd_ST_Accel_Class_3M', 'Sector','Fwd_Best_EPS_6M', 'Fwd_Best_EPS_6M_v5Y','Fwd_Return_6M', 'Fwd_Return_3M', 'Fwd_Return_1M'])
df3.describe()

,Fwd_ST_Accel_3M,Mkt_Cap,Best_EPS_1M,Best_EPS_3M,Best_EPS_6M,Best_EPS_1Y,Best_EPS_3Y,Best_EPS_5Y,Best_EPS_3M_v5Y,Best_EPS_6M_v5Y,...,ROIC_SD,ROE,ROE_1Y_Chg,ROE_SD,FCF_Mgn,FCF_Mgn_1Y_Chg,FCF_Mgn_SD,Op_Mgn,Op_Mgn_1Y_Chg,Op_Mgn_SD
count,9655.000000,9.655000e+03,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,...,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000,9655.000000
mean,52.130433,4.873435e+04,0.131042,0.154172,0.104790,0.082954,0.189046,0.224295,0.623089,0.373428,...,4.436768,23.128603,0.714566,10.081576,16.712635,1.599437,5.077914,19.949077,0.241283,2.256996
std,21.826487,1.589189e+05,0.712215,0.440149,0.274208,0.182191,0.151355,0.221054,2.415437,1.432303,...,12.549713,20.775341,15.693921,28.630527,17.378893,9.759347,15.022525,11.868889,3.391683,2.924381
min,0.000000,4.562085e+02,-2.926829,-1.384615,-0.919422,-0.442396,-0.170858,-0.107213,-7.953953,-3.993373,...,0.102878,-12.375649,-472.845019,0.240854,-53.640777,-138.502299,0.277630,0.991808,-31.670424,0.043836
25%,35.100000,4.665172e+03,-0.011928,-0.016713,-0.044319,-0.018127,0.090515,0.100719,-0.068293,-0.211718,...,1.594859,11.220107,-2.717843,2.261763,7.884683,-1.286033,1.828516,10.670374,-0.774170,0.908480
50%,52.266667,1.350816e+04,0.000000,0.107740,0.076464,0.068636,0.157016,0.162899,0.527363,0.384920,...,2.623948,16.978441,0.073115,4.078987,14.462899,1.429506,2.987927,17.819475,0.275584,1.481325
75%,68.450000,3.294946e+04,0.129252,0.333115,0.222041,0.164483,0.253289,0.265465,1.883838,1.256368,...,4.350258,27.836253,3.284567,9.001750,25.205843,4.321343,4.692301,26.382385,1.499902,2.888305
max,99.166667,2.138671e+06,5.963361,3.557447,1.901235,1.970179,1.952381,1.984000,7.994405,3.994267,...,267.476144,171.365332,118.384365,483.121134,189.810606,276.603059,268.684445,70.454544,26.242878,54.359769

In [18]:
reg_experiment = setup(df3, target = 'Fwd_ST_Accel_3M', session_id=123, log_experiment=True, experiment_name='Fwd_ST_Accel_3M')

In [19]:
best_model = compare_models(fold=10)

In [20]:
cat3 = create_model('catboost')

In [21]:
evaluate_model(cat3)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦